[project]
name = "option-pricing-engine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "loridelotto", email = "lorenzo.delotto@mail.polimi.it" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
option-pricing-engine = "option_pricing_engine:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
